services:
  mysqldb:
    image: mysql:8.0
    container_name: mysql_container
    restart: always
    ports:
      - 3308:3306
    env_file:
      - .env

    volumes:
      - mysql_data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 5s
      timeout: 5s
      retries: 3

volumes:
  mysql_data:
