@CashFlow.API_HostAddress = https://localhost:8081
@ACCESS_JWT =
@Expense_Id = 13

###

POST {{CashFlow.API_HostAddress}}/login
Content-Type: application/json

{
  "email": "richard@mail.com",
  "password": "!Richard1234"
}

###

GET {{CashFlow.API_HostAddress}}/user
Authorization: Bearer {{ACCESS_JWT}}

###

POST {{CashFlow.API_HostAddress}}/login
Content-Type: application/json

{
  "email": "volibear@mail.com",
  "password": "!Password123"
}

###

POST {{CashFlow.API_HostAddress}}/user
Content-Type: application/json

{
  "name": "Volibear",
  "email": "volibear@mail.com",
  "password": "!Password123"
}

###

POST {{CashFlow.API_HostAddress}}/expenses
Content-Type: application/json
Authorization: Bearer {{ACCESS_JWT}}

{
  "title": "iphone 11",
  "description": "description iphone 11",
  "date": "2025-01-05T20:16:30.351Z",
  "amount": 200,
  "paymentType": 1
}

###

PUT {{CashFlow.API_HostAddress}}/expenses/{{Expense_Id}}
Content-Type: application/json
Authorization: Bearer {{ACCESS_JWT}}

{
  "title": "iphone 11 modificado",
  "description": "description iphone 11",
  "date": "2025-01-05",
  "amount": 1200,
  "paymentType": 1
}

###

GET {{CashFlow.API_HostAddress}}/expenses
Authorization: Bearer {{ACCESS_JWT}}

### 

GET {{CashFlow.API_HostAddress}}/expenses/{{Expense_Id}}
Authorization: Bearer {{ACCESS_JWT}}

###

DELETE {{CashFlow.API_HostAddress}}/expenses/{{Expense_Id}}
Authorization: Bearer {{ACCESS_JWT}}

### 

GET {{CashFlow.API_HostAddress}}/report/pdf
Authorization: Bearer {{ACCESS_JWT}}
Accept-Language: pt-BR
month: 2025-01

###

GET {{CashFlow.API_HostAddress}}/report/excel
Authorization: Bearer {{ACCESS_JWT}}
Accept-Language: pt-BR
month: 2025-01
  