@CashFlow.API_HostAddress = https://localhost:8081
@ACCESS_JWT = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1bmlxdWVfbmFtZSI6IlJpY2hhcmQiLCJodHRwOi8vc2NoZW1hcy54bWxzb2FwLm9yZy93cy8yMDA1LzA1L2lkZW50aXR5L2NsYWltcy9zaWQiOiI4NWJhYjMxYi01YjViLTQ5OWMtOWIzOS03MjNhYWE3OTgzMTciLCJuYmYiOjE3MzYwMTA3MzEsImV4cCI6MTczNjA3MDczMSwiaWF0IjoxNzM2MDEwNzMxfQ.5lioZPjLUBYg7CIC7CJaRi7TvtFkEhD35Xzx7-E9siw

###

POST {{CashFlow.API_HostAddress}}/login
Content-Type: application/json

{
  "email": "richard@mail.com",
  "password": "!Richard123"
}

###

POST {{CashFlow.API_HostAddress}}/expenses
Content-Type: application/json
Authorization: Bearer {{ACCESS_JWT}}

{
  "title": "iphone 11",
  "description": "description iphone 11",
  "date": "2025-01-04T01:17:01.629Z",
  "amount": 200,
  "paymentType": 1
}